summary: XML-based font configuration tools
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-13.0-arm64/releases/download/2024.05.29/fontconfig-2.15.0-macos-13.0-arm64.tar.xz
bin-sha: 4dd28b93e2813bb538a3cfe5ce7d9d6d4e817153136ce74bd8167a3e1d160f43
