summary: XML-based font configuration library
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-13.0-arm64/releases/download/2024.05.29/libfontconfig-2.15.0-macos-13.0-arm64.tar.xz
bin-sha: 9157255370bb6d599d23ef4ff8d823fc14a4c5ad4f511452cbcbd2607d49f629
