summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-macos13.0-arm64/releases/download/2023.04.07/pkg-config-0.29.2-macos13.0-arm64.tar.xz
bin-sha: 8876d5cbe2a17ce7c71db969e250e94ce627c758abf59c9518b9f0a23efad21c
