summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-13.0-arm64/releases/download/2024.06.14/pkg-config-0.29.2-macos-13.0-arm64.tar.xz
bin-sha: 11a6a19861fa620f863f568117e977a0c5aa5ca6cc149c470058fc78a82d5e99
